
services:
  server:
    build:
      context: .
    command: >
      sh -c "poetry run python auto_migrate.py &&
              poetry run uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    volumes:
      - alembic_versions:/app/alembic/versions 
    networks:
      - credit_network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: always
    user: postgres
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - credit_network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  alembic_versions:
secrets:
  db-password:
    file: db/password.txt
networks:
  credit_network:
    driver: bridge
